# Makefile 06 - User flags

# Copyright (c) 2015, Monaco F. J. <monaco@.usp.br>
#
# This file is part of POSIXeg.
#
# POSIXeg is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Objects

OBJECTS = main.o simpson_e_newton.o

BIN = main

# Maintainer flags

CPP_FLAGS = -I.
C_FLAGS =
LD_FLAGS = -lm
CC = gcc

# Default target

all: $(BIN)

# Binary

$(BIN) : $(OBJECTS)
	$(CC) $(LD_FLAGS) $(LDFLAGS) $^ -o $@

# Pattern rule for object-source dependences

%.o : %.c
	$(CC) $(CPP_FLAGS) $(CPPFLAGS) $(C_FLAGS) $(CFLAGS)-c $<

# Automatic object-header dependences

makefiles = $(OBJECTS:%.o=%.d)

include $(makefiles)

%.d : %.c
	$(CC) $(CPP_FLAGS) $(CPPFLAGS) -c $<  -MM -MT '$(<:.c=.o) $@' $< >$@

run:
	@./main

# Cleaning

.PHONY : clean

clean:
	rm -f $(OBJECTS) $(BIN) *.d
	rm -f *~ \#*
